package main

import (
	"database/sql"
	"fmt"
)

// SqlResponse encapsulates a response generated by a worker
type SqlResponse struct {
	err    bool
	result string
}

// WorkItem encapsulates a job sent to a worker
type WorkItem struct {
	request    string
	geojson    bool
	pretty     bool
	collection bool
	response   chan SqlResponse
}

// worker function that executes SQL queries
func worker(db *sql.DB, worker_id int, tasks <-chan WorkItem) {

	var res string

	// reads job from channel
	for task := range tasks {
		// log.Printf("worker %d processing task '%s'\n", id, task.request)

		// this executes the request on the database.
		var rows *sql.Rows
		var err error

		if !task.collection {

			// if task.collection is not set, we execute the query as-is.
			// this will only work if the query returns exactly one row and one column.
			rows, err = db.Query(task.request)

		} else if task.geojson && task.pretty {

			// this generates prettified GeoJSON

			rows, err = db.Query(fmt.Sprintf(
				`SELECT jsonb_pretty(jsonb_build_object( 
                    'type', 'FeatureCollection', 
                    'properties', json_build_object(
                       'timestamp', (select value from osm2pgsql_properties where property='replication_timestamp'),
                       'generator', 'Postpass API 0.1'
                       ), 
                    'features', coalesce(json_agg(ST_AsGeoJSON(t.*)::json), '[]'::json)))
                FROM (%s) as t;`, task.request))

		} else if task.geojson && !task.pretty {

			// this generates un-prettified GeoJSON

			rows, err = db.Query(fmt.Sprintf(
				`SELECT json_build_object( 
                    'type', 'FeatureCollection', 
                    'properties', json_build_object(
                       'timestamp', (select value from osm2pgsql_properties where property='replication_timestamp'),
                       'generator', 'Postpass API 0.1'
                       ), 
                    'features', coalesce(json_agg(ST_AsGeoJSON(t.*)::json), '[]'::json))
                FROM (%s) as t;`, task.request))

		} else {

			// this collects results over multiple rows and columns,
			// but doesn't attempt to build GeoJSON

			rows, err = db.Query(fmt.Sprintf(
				`SELECT jsonb_pretty(jsonb_build_object( 
                    'metadata', json_build_object(
                       'timestamp', (select value from osm2pgsql_properties where property='replication_timestamp'),
                       'generator', 'Postpass API 0.1'
                       ), 
                    'result', json_agg(t.*)::json))  
                FROM (%s) as t;`, task.request))
		}

		if err != nil {
			task.response <- SqlResponse{err: true, result: err.Error()}
			return
		}

		// parse only one line of results
		rows.Next()

		// scan only one column of the result line
		err = rows.Scan(&res)

		// discard result
		rows.Close()

		if err != nil {
			task.response <- SqlResponse{err: true, result: err.Error()}
			return
		}

		// log.Printf("worker %d done\n", id)

		// send response back on channel
		task.response <- SqlResponse{err: false, result: res}
	}
}
